import pg from "pg";

const { Pool } = pg;
const databaseUrl = process.env.DATABASE_URL;
const databaseHost = process.env.DB_HOST;
const isLocalHost = !databaseHost || ["localhost", "127.0.0.1", "::1"].includes(databaseHost);
const useSsl = process.env.DB_SSL
  ? process.env.DB_SSL === "true"
  : Boolean(databaseUrl || !isLocalHost);

export const pool = new Pool({
  connectionString: databaseUrl,
  host: databaseHost,
  database: process.env.DB_NAME || "postgres",
  user: process.env.DB_USER,
  password: process.env.DB_PASSWORD,
  port: Number(process.env.DB_PORT || 5432),
  max: Number(process.env.DB_POOL_MAX || 1),
  connectionTimeoutMillis: Number(process.env.DB_CONNECTION_TIMEOUT_MS || 5000),
  ssl: useSsl ? { rejectUnauthorized: false } : false,
});

export async function initDatabase() {
  if (!databaseUrl && !process.env.DB_HOST) {
    throw new Error("Database configuration requires DB_HOST or DATABASE_URL in .env");
  }

  await repairLegacyPlannerSchema();
  const hasTrigram = await ensureTrigramExtension();

  await pool.query(`
    create table if not exists daily_user (
      id bigint generated by default as identity primary key,
      name text not null,
      password_hash text not null,
      is_admin boolean not null default false,
      created_at timestamptz not null default now(),
      constraint daily_user_name_required check (length(trim(name)) > 0)
    );

    create unique index if not exists daily_user_name_ci_uidx
      on daily_user (lower(trim(name)));

    create table if not exists daily_task (
      id bigint generated by default as identity primary key,
      user_id bigint not null references daily_user(id) on delete cascade,
      subject text not null,
      parent_subject text not null,
      task_date date not null,
      estimated_minutes integer not null,
      actual_minutes integer,
      focused_seconds integer not null default 0,
      pomodoro_count integer not null default 0,
      start_time text,
      sort_time text not null default '99:99',
      priority text not null default 'low',
      notes text not null default '',
      status text not null default 'planned',
      created_at timestamptz not null default now(),
      completed_at timestamptz,
      backlog_at timestamptz,
      constraint daily_task_subject_required check (length(trim(subject)) > 0),
      constraint daily_task_parent_subject_required check (length(trim(parent_subject)) > 0),
      constraint daily_task_estimate_positive check (estimated_minutes > 0),
      constraint daily_task_actual_positive check (actual_minutes is null or actual_minutes > 0),
      constraint daily_task_focused_seconds_valid check (focused_seconds >= 0),
      constraint daily_task_pomodoro_count_valid check (pomodoro_count >= 0),
      constraint daily_task_priority_valid check (priority in ('low', 'medium', 'high')),
      constraint daily_task_status_valid check (status in ('planned', 'completed', 'backlog'))
    );

    create index if not exists daily_task_user_date_sort_idx
      on daily_task (user_id, task_date desc, sort_time, created_at desc);

    create index if not exists daily_task_user_status_date_idx
      on daily_task (user_id, status, task_date desc);

    create index if not exists daily_task_user_parent_subject_idx
      on daily_task (user_id, parent_subject);

    create table if not exists daily_pomodoro_session (
      id bigint generated by default as identity primary key,
      user_id bigint not null references daily_user(id) on delete cascade,
      task_id bigint not null references daily_task(id) on delete cascade,
      mode text not null default 'focus',
      status text not null default 'running',
      duration_seconds integer not null,
      remaining_seconds integer not null,
      elapsed_seconds integer not null default 0,
      started_at timestamptz not null default now(),
      ends_at timestamptz,
      completed_at timestamptz,
      created_at timestamptz not null default now(),
      constraint daily_pomodoro_mode_valid check (mode in ('focus', 'short_break', 'long_break')),
      constraint daily_pomodoro_status_valid check (status in ('running', 'paused', 'completed', 'cancelled')),
      constraint daily_pomodoro_duration_positive check (duration_seconds > 0),
      constraint daily_pomodoro_remaining_valid check (remaining_seconds >= 0),
      constraint daily_pomodoro_elapsed_valid check (elapsed_seconds >= 0)
    );

    create unique index if not exists daily_pomodoro_one_active_user_uidx
      on daily_pomodoro_session (user_id)
      where status in ('running', 'paused');

    create index if not exists daily_pomodoro_user_history_idx
      on daily_pomodoro_session (user_id, created_at desc);

    create index if not exists daily_pomodoro_task_history_idx
      on daily_pomodoro_session (task_id, created_at desc);

    create index if not exists daily_pomodoro_running_expiry_idx
      on daily_pomodoro_session (ends_at)
      where status = 'running';

    create table if not exists daily_setting (
      id text primary key,
      daily_target_minutes integer not null default 240,
      weekly_target_minutes integer not null default 1200,
      updated_at timestamptz not null default now(),
      constraint daily_setting_daily_target_positive check (daily_target_minutes > 0),
      constraint daily_setting_weekly_target_positive check (weekly_target_minutes > 0)
    );

    insert into daily_setting (id)
    select 'shared_dashboard'
    where not exists (
      select 1 from daily_setting where id = 'shared_dashboard'
    );

    create table if not exists fin_asset (
      id bigint generated by default as identity primary key,
      user_id bigint not null references daily_user(id) on delete cascade,
      name text not null,
      symbol text not null,
      exchange text not null default 'NSE',
      sector text not null default '',
      notes text not null default '',
      last_price numeric(18, 4),
      last_price_at timestamptz,
      created_at timestamptz not null default now(),
      updated_at timestamptz not null default now(),
      constraint fin_asset_name_required check (length(trim(name)) > 0),
      constraint fin_asset_symbol_required check (length(trim(symbol)) > 0)
    );

    create unique index if not exists fin_asset_user_symbol_exchange_uidx
      on fin_asset (user_id, upper(trim(symbol)), upper(trim(exchange)));

    create index if not exists fin_asset_user_updated_idx
      on fin_asset (user_id, updated_at desc);

    create index if not exists fin_asset_user_exchange_idx
      on fin_asset (user_id, exchange);

    create index if not exists fin_asset_user_last_price_idx
      on fin_asset (user_id, last_price_at desc)
      where last_price is not null;

    create table if not exists fin_transaction (
      id bigint generated by default as identity primary key,
      user_id bigint not null references daily_user(id) on delete cascade,
      asset_id bigint not null references fin_asset(id) on delete cascade,
      transaction_date date not null,
      transaction_type text not null,
      quantity numeric(18, 6) not null default 0,
      price numeric(18, 4) not null default 0,
      charges numeric(18, 4) not null default 0,
      notes text not null default '',
      created_at timestamptz not null default now(),
      updated_at timestamptz not null default now(),
      constraint fin_transaction_type_valid check (transaction_type in ('buy', 'sell', 'dividend', 'fee')),
      constraint fin_transaction_quantity_valid check (
        (transaction_type in ('buy', 'sell') and quantity > 0)
        or (transaction_type in ('dividend', 'fee') and quantity >= 0)
      ),
      constraint fin_transaction_price_valid check (
        (transaction_type in ('buy', 'sell') and price > 0)
        or (transaction_type in ('dividend', 'fee') and price >= 0)
      ),
      constraint fin_transaction_charges_valid check (charges >= 0)
    );

    create index if not exists fin_transaction_user_date_idx
      on fin_transaction (user_id, transaction_date desc, created_at desc);

    create index if not exists fin_transaction_asset_date_idx
      on fin_transaction (asset_id, transaction_date asc, created_at asc);

    create index if not exists fin_transaction_user_asset_date_idx
      on fin_transaction (user_id, asset_id, transaction_date asc, created_at asc);

    create index if not exists fin_transaction_user_type_date_idx
      on fin_transaction (user_id, transaction_type, transaction_date desc);

    create index if not exists fin_transaction_user_asset_type_idx
      on fin_transaction (user_id, asset_id, transaction_type);

    create table if not exists fin_portfolio_snapshot (
      id bigint generated by default as identity primary key,
      user_id bigint not null references daily_user(id) on delete cascade,
      snapshot_type text not null,
      snapshot_date date not null,
      period_start date not null,
      period_end date not null,
      current_value numeric(18, 4) not null default 0,
      invested_value numeric(18, 4) not null default 0,
      total_profit numeric(18, 4) not null default 0,
      profit_percent numeric(18, 6) not null default 0,
      realized_profit numeric(18, 4) not null default 0,
      unrealized_profit numeric(18, 4) not null default 0,
      total_charges numeric(18, 4) not null default 0,
      holding_count integer not null default 0,
      sold_count integer not null default 0,
      holdings jsonb not null default '[]'::jsonb,
      allocation jsonb not null default '[]'::jsonb,
      sectors jsonb not null default '[]'::jsonb,
      period_profit numeric(18, 4) not null default 0,
      period_return_percent numeric(18, 6),
      nifty_start_value numeric(18, 4),
      nifty_end_value numeric(18, 4),
      nifty_return_percent numeric(18, 6),
      alpha_percent numeric(18, 6),
      benchmark jsonb not null default '{}'::jsonb,
      captured_at timestamptz not null default now(),
      constraint fin_portfolio_snapshot_type_valid check (snapshot_type in ('daily', 'weekly', 'monthly', 'fiscal_year')),
      constraint fin_portfolio_snapshot_period_valid check (period_start <= period_end),
      constraint fin_portfolio_snapshot_counts_valid check (holding_count >= 0 and sold_count >= 0)
    );

    create unique index if not exists fin_portfolio_snapshot_user_type_date_uidx
      on fin_portfolio_snapshot (user_id, snapshot_type, snapshot_date);

    create index if not exists fin_portfolio_snapshot_user_date_idx
      on fin_portfolio_snapshot (user_id, snapshot_date desc, captured_at desc);

    create index if not exists fin_portfolio_snapshot_user_type_date_idx
      on fin_portfolio_snapshot (user_id, snapshot_type, snapshot_date desc);

    create table if not exists daily_batch_schedule (
      batch_id text primary key,
      cron_expression text not null,
      enabled boolean not null default true,
      updated_at timestamptz not null default now()
    );

    create table if not exists app_log (
      id bigint generated by default as identity primary key,
      level text not null default 'info',
      event text not null,
      message text not null default '',
      request_id text,
      user_id bigint,
      method text,
      path text,
      status_code integer,
      duration_ms integer,
      meta jsonb not null default '{}'::jsonb,
      created_at timestamptz not null default now(),
      constraint app_log_level_valid check (level in ('info', 'warn', 'error'))
    );

    create index if not exists app_log_created_idx on app_log (created_at desc);
    create index if not exists app_log_level_created_idx on app_log (level, created_at desc);

    create table if not exists fin_batch_run (
      id bigint generated by default as identity primary key,
      batch_id text not null,
      run_source text not null default 'manual',
      run_status text not null default 'running',
      started_at timestamptz not null default now(),
      finished_at timestamptz,
      duration_ms integer,
      result jsonb not null default '{}'::jsonb,
      error_message text,
      created_at timestamptz not null default now(),
      constraint fin_batch_run_status_valid check (run_status in ('running', 'success', 'failed', 'skipped'))
    );

    create index if not exists fin_batch_run_started_idx on fin_batch_run (started_at desc);
    create index if not exists fin_batch_run_batch_started_idx on fin_batch_run (batch_id, started_at desc);

  `);

  await pool.query(`
    alter table fin_portfolio_snapshot add column if not exists period_profit numeric(18, 4) not null default 0;
    alter table fin_portfolio_snapshot add column if not exists period_return_percent numeric(18, 6);
    alter table fin_portfolio_snapshot add column if not exists nifty_start_value numeric(18, 4);
    alter table fin_portfolio_snapshot add column if not exists nifty_end_value numeric(18, 4);
    alter table fin_portfolio_snapshot add column if not exists nifty_return_percent numeric(18, 6);
    alter table fin_portfolio_snapshot add column if not exists alpha_percent numeric(18, 6);
    alter table fin_portfolio_snapshot add column if not exists benchmark jsonb not null default '{}'::jsonb;
  `);

  if (hasTrigram) {
    await pool.query(`
      create index if not exists fin_asset_name_trgm_idx
        on fin_asset using gin (lower(name) gin_trgm_ops);

      create index if not exists fin_asset_symbol_trgm_idx
        on fin_asset using gin (lower(symbol) gin_trgm_ops);

      create index if not exists fin_asset_sector_trgm_idx
        on fin_asset using gin (lower(sector) gin_trgm_ops);

    `);
  }
}

async function ensureTrigramExtension() {
  try {
    await pool.query("create extension if not exists pg_trgm");
    return true;
  } catch (error) {
    console.warn("Finance search trigram indexes skipped:", error.message);
    return false;
  }
}

async function repairLegacyPlannerSchema() {
  await pool.query(`
    do $$
    begin
      if to_regclass('public.daily_user') is not null then
        alter table public.daily_user alter column id set not null;
        alter table public.daily_user alter column name set not null;
        alter table public.daily_user alter column password_hash set not null;
        alter table public.daily_user alter column is_admin set default false;
        update public.daily_user set is_admin = false where is_admin is null;
        alter table public.daily_user alter column is_admin set not null;
        alter table public.daily_user alter column created_at set default now();
        update public.daily_user set created_at = now() where created_at is null;
        alter table public.daily_user alter column created_at set not null;

        if not exists (
          select 1
          from pg_constraint
          where conrelid = 'public.daily_user'::regclass
            and contype = 'p'
        ) then
          alter table public.daily_user add constraint daily_user_pkey primary key (id);
        end if;

        if not exists (
          select 1
          from pg_constraint
          where conrelid = 'public.daily_user'::regclass
            and conname = 'daily_user_name_required'
        ) then
          alter table public.daily_user
            add constraint daily_user_name_required check (length(trim(name)) > 0);
        end if;
      end if;

      if to_regclass('public.daily_task') is not null then
        alter table public.daily_task alter column id set not null;

        if not exists (
          select 1
          from pg_constraint
          where conrelid = 'public.daily_task'::regclass
            and contype = 'p'
        ) then
          alter table public.daily_task add constraint daily_task_pkey primary key (id);
        end if;
      end if;

      if to_regclass('public.fin_asset') is not null then
        alter table public.fin_asset drop constraint if exists fin_asset_exchange_valid;
      end if;
    end $$;
  `);
}
