import pg from "pg";

const { Pool } = pg;
const databaseUrl = process.env.DATABASE_URL;
const databaseHost = process.env.DB_HOST;
const isLocalHost = !databaseHost || ["localhost", "127.0.0.1", "::1"].includes(databaseHost);
const useSsl = process.env.DB_SSL
  ? process.env.DB_SSL === "true"
  : Boolean(databaseUrl || !isLocalHost);

export const pool = new Pool({
  connectionString: databaseUrl,
  host: databaseHost,
  database: process.env.DB_NAME || "postgres",
  user: process.env.DB_USER,
  password: process.env.DB_PASSWORD,
  port: Number(process.env.DB_PORT || 5432),
  max: Number(process.env.DB_POOL_MAX || 1),
  connectionTimeoutMillis: Number(process.env.DB_CONNECTION_TIMEOUT_MS || 5000),
  ssl: useSsl ? { rejectUnauthorized: false } : false,
});

export async function initDatabase() {
  if (!databaseUrl && !process.env.DB_HOST) {
    throw new Error("Database configuration requires DB_HOST or DATABASE_URL in .env");
  }

  await repairLegacyPlannerSchema();
  const hasTrigram = await ensureTrigramExtension();

  await pool.query(`
    create table if not exists daily_user (
      id bigint generated by default as identity primary key,
      name text not null,
      password_hash text not null,
      is_admin boolean not null default false,
      created_at timestamptz not null default now(),
      constraint daily_user_name_required check (length(trim(name)) > 0)
    );

    create unique index if not exists daily_user_name_ci_uidx
      on daily_user (lower(trim(name)));

    create table if not exists daily_task (
      id bigint generated by default as identity primary key,
      user_id bigint not null references daily_user(id) on delete cascade,
      subject text not null,
      parent_subject text not null,
      task_date date not null,
      estimated_minutes integer not null,
      actual_minutes integer,
      focused_seconds integer not null default 0,
      pomodoro_count integer not null default 0,
      start_time text,
      sort_time text not null default '99:99',
      priority text not null default 'low',
      notes text not null default '',
      status text not null default 'planned',
      created_at timestamptz not null default now(),
      completed_at timestamptz,
      backlog_at timestamptz,
      constraint daily_task_subject_required check (length(trim(subject)) > 0),
      constraint daily_task_parent_subject_required check (length(trim(parent_subject)) > 0),
      constraint daily_task_estimate_positive check (estimated_minutes > 0),
      constraint daily_task_actual_positive check (actual_minutes is null or actual_minutes > 0),
      constraint daily_task_focused_seconds_valid check (focused_seconds >= 0),
      constraint daily_task_pomodoro_count_valid check (pomodoro_count >= 0),
      constraint daily_task_priority_valid check (priority in ('low', 'medium', 'high')),
      constraint daily_task_status_valid check (status in ('planned', 'completed', 'backlog'))
    );

    create index if not exists daily_task_user_date_sort_idx
      on daily_task (user_id, task_date desc, sort_time, created_at desc);

    create index if not exists daily_task_user_status_date_idx
      on daily_task (user_id, status, task_date desc);

    create index if not exists daily_task_user_parent_subject_idx
      on daily_task (user_id, parent_subject);

    create table if not exists daily_pomodoro_session (
      id bigint generated by default as identity primary key,
      user_id bigint not null references daily_user(id) on delete cascade,
      task_id bigint not null references daily_task(id) on delete cascade,
      mode text not null default 'focus',
      status text not null default 'running',
      duration_seconds integer not null,
      remaining_seconds integer not null,
      elapsed_seconds integer not null default 0,
      started_at timestamptz not null default now(),
      ends_at timestamptz,
      completed_at timestamptz,
      created_at timestamptz not null default now(),
      constraint daily_pomodoro_mode_valid check (mode in ('focus', 'short_break', 'long_break')),
      constraint daily_pomodoro_status_valid check (status in ('running', 'paused', 'completed', 'cancelled')),
      constraint daily_pomodoro_duration_positive check (duration_seconds > 0),
      constraint daily_pomodoro_remaining_valid check (remaining_seconds >= 0),
      constraint daily_pomodoro_elapsed_valid check (elapsed_seconds >= 0)
    );

    create unique index if not exists daily_pomodoro_one_active_user_uidx
      on daily_pomodoro_session (user_id)
      where status in ('running', 'paused');

    create index if not exists daily_pomodoro_user_history_idx
      on daily_pomodoro_session (user_id, created_at desc);

    create index if not exists daily_pomodoro_task_history_idx
      on daily_pomodoro_session (task_id, created_at desc);

    create index if not exists daily_pomodoro_running_expiry_idx
      on daily_pomodoro_session (ends_at)
      where status = 'running';

    create table if not exists daily_setting (
      id text primary key,
      daily_target_minutes integer not null default 240,
      weekly_target_minutes integer not null default 1200,
      updated_at timestamptz not null default now(),
      constraint daily_setting_daily_target_positive check (daily_target_minutes > 0),
      constraint daily_setting_weekly_target_positive check (weekly_target_minutes > 0)
    );

    insert into daily_setting (id)
    select 'shared_dashboard'
    where not exists (
      select 1 from daily_setting where id = 'shared_dashboard'
    );

    create table if not exists fin_asset (
      id bigint generated by default as identity primary key,
      user_id bigint not null references daily_user(id) on delete cascade,
      name text not null,
      symbol text not null,
      exchange text not null default 'NSE',
      sector text not null default '',
      notes text not null default '',
      last_price numeric(18, 4),
      last_price_at timestamptz,
      created_at timestamptz not null default now(),
      updated_at timestamptz not null default now(),
      constraint fin_asset_name_required check (length(trim(name)) > 0),
      constraint fin_asset_symbol_required check (length(trim(symbol)) > 0)
    );

    create unique index if not exists fin_asset_user_symbol_exchange_uidx
      on fin_asset (user_id, upper(trim(symbol)), upper(trim(exchange)));

    create index if not exists fin_asset_user_updated_idx
      on fin_asset (user_id, updated_at desc);

    create index if not exists fin_asset_user_exchange_idx
      on fin_asset (user_id, exchange);

    create index if not exists fin_asset_user_last_price_idx
      on fin_asset (user_id, last_price_at desc)
      where last_price is not null;

    create table if not exists fin_transaction (
      id bigint generated by default as identity primary key,
      user_id bigint not null references daily_user(id) on delete cascade,
      asset_id bigint not null references fin_asset(id) on delete cascade,
      transaction_date date not null,
      transaction_type text not null,
      quantity numeric(18, 6) not null default 0,
      price numeric(18, 4) not null default 0,
      charges numeric(18, 4) not null default 0,
      notes text not null default '',
      created_at timestamptz not null default now(),
      updated_at timestamptz not null default now(),
      constraint fin_transaction_type_valid check (transaction_type in ('buy', 'sell', 'dividend', 'fee')),
      constraint fin_transaction_quantity_valid check (
        (transaction_type in ('buy', 'sell') and quantity > 0)
        or (transaction_type in ('dividend', 'fee') and quantity >= 0)
      ),
      constraint fin_transaction_price_valid check (
        (transaction_type in ('buy', 'sell') and price > 0)
        or (transaction_type in ('dividend', 'fee') and price >= 0)
      ),
      constraint fin_transaction_charges_valid check (charges >= 0)
    );

    create index if not exists fin_transaction_user_date_idx
      on fin_transaction (user_id, transaction_date desc, created_at desc);

    create index if not exists fin_transaction_asset_date_idx
      on fin_transaction (asset_id, transaction_date asc, created_at asc);

    create index if not exists fin_transaction_user_asset_date_idx
      on fin_transaction (user_id, asset_id, transaction_date asc, created_at asc);

    create index if not exists fin_transaction_user_type_date_idx
      on fin_transaction (user_id, transaction_type, transaction_date desc);

    create index if not exists fin_transaction_user_asset_type_idx
      on fin_transaction (user_id, asset_id, transaction_type);

    create table if not exists fin_insider_trade (
      id bigint generated by default as identity primary key,
      dedupe_key text not null,
      source text not null,
      source_record_id text not null default '',
      symbol text not null default '',
      company text not null,
      person text not null default '',
      category text not null default '',
      transaction_type text not null default '',
      acquisition_mode text not null default '',
      quantity numeric(30, 6) not null default 0,
      transaction_value numeric(30, 4) not null default 0,
      activity_date date not null,
      disclosure_date date,
      disclosure_url text not null default '',
      holding_before_percent numeric(12, 6),
      holding_after_percent numeric(12, 6),
      market_cap_impact_percent numeric(14, 8),
      created_at timestamptz not null default now(),
      updated_at timestamptz not null default now(),
      constraint fin_insider_trade_company_required check (length(trim(company)) > 0),
      constraint fin_insider_trade_source_valid check (source in ('NSE', 'BSE')),
      constraint fin_insider_trade_quantity_valid check (quantity >= 0),
      constraint fin_insider_trade_value_valid check (transaction_value >= 0)
    );

    create unique index if not exists fin_insider_trade_dedupe_uidx
      on fin_insider_trade (dedupe_key);

    create index if not exists fin_insider_trade_activity_idx
      on fin_insider_trade (activity_date desc, id desc);

    create index if not exists fin_insider_trade_disclosure_idx
      on fin_insider_trade (disclosure_date desc, id desc);

    create index if not exists fin_insider_trade_symbol_idx
      on fin_insider_trade (upper(symbol), activity_date desc);

    create index if not exists fin_insider_trade_company_idx
      on fin_insider_trade (lower(company), activity_date desc);

    create index if not exists fin_insider_trade_type_activity_idx
      on fin_insider_trade (transaction_type, activity_date desc, id desc);

    create index if not exists fin_insider_trade_source_disclosure_idx
      on fin_insider_trade (source, disclosure_date desc, id desc);

    create table if not exists fin_insider_sync_state (
      id text primary key,
      last_from_date date,
      last_to_date date,
      last_success_at timestamptz,
      last_inserted integer not null default 0,
      last_seen integer not null default 0,
      last_error text not null default '',
      status text not null default 'idle',
      current_label text not null default '',
      from_year integer,
      to_year integer,
      total_windows integer not null default 0,
      completed_windows integer not null default 0,
      failed_windows integer not null default 0,
      progress_received integer not null default 0,
      progress_inserted integer not null default 0,
      progress_updated integer not null default 0,
      progress_ignored integer not null default 0,
      started_at timestamptz,
      completed_at timestamptz,
      updated_at timestamptz not null default now()
    );

    alter table fin_insider_sync_state add column if not exists status text not null default 'idle';
    alter table fin_insider_sync_state add column if not exists current_label text not null default '';
    alter table fin_insider_sync_state add column if not exists from_year integer;
    alter table fin_insider_sync_state add column if not exists to_year integer;
    alter table fin_insider_sync_state add column if not exists total_windows integer not null default 0;
    alter table fin_insider_sync_state add column if not exists completed_windows integer not null default 0;
    alter table fin_insider_sync_state add column if not exists failed_windows integer not null default 0;
    alter table fin_insider_sync_state add column if not exists progress_received integer not null default 0;
    alter table fin_insider_sync_state add column if not exists progress_inserted integer not null default 0;
    alter table fin_insider_sync_state add column if not exists progress_updated integer not null default 0;
    alter table fin_insider_sync_state add column if not exists progress_ignored integer not null default 0;
    alter table fin_insider_sync_state add column if not exists started_at timestamptz;
    alter table fin_insider_sync_state add column if not exists completed_at timestamptz;

    create index if not exists fin_insider_sync_state_status_idx
      on fin_insider_sync_state (status, updated_at desc);

    alter table fin_insider_trade add column if not exists holding_before_percent numeric(12, 6);
    alter table fin_insider_trade add column if not exists holding_after_percent numeric(12, 6);
    alter table fin_insider_trade add column if not exists market_cap_impact_percent numeric(14, 8);
  `);

  if (hasTrigram) {
    await pool.query(`
      create index if not exists fin_asset_name_trgm_idx
        on fin_asset using gin (lower(name) gin_trgm_ops);

      create index if not exists fin_asset_symbol_trgm_idx
        on fin_asset using gin (lower(symbol) gin_trgm_ops);

      create index if not exists fin_asset_sector_trgm_idx
        on fin_asset using gin (lower(sector) gin_trgm_ops);

      create index if not exists fin_insider_trade_identity_search_trgm_idx
        on fin_insider_trade using gin (
          lower(symbol || ' ' || company) gin_trgm_ops
        );

      create index if not exists fin_insider_trade_full_search_trgm_idx
        on fin_insider_trade using gin (
          lower(symbol || ' ' || company || ' ' || person || ' ' || category || ' ' || transaction_type || ' ' || acquisition_mode) gin_trgm_ops
        );
    `);
  }
}

async function ensureTrigramExtension() {
  try {
    await pool.query("create extension if not exists pg_trgm");
    return true;
  } catch (error) {
    console.warn("Finance search trigram indexes skipped:", error.message);
    return false;
  }
}

async function repairLegacyPlannerSchema() {
  await pool.query(`
    do $$
    begin
      if to_regclass('public.daily_user') is not null then
        alter table public.daily_user alter column id set not null;
        alter table public.daily_user alter column name set not null;
        alter table public.daily_user alter column password_hash set not null;
        alter table public.daily_user alter column is_admin set default false;
        update public.daily_user set is_admin = false where is_admin is null;
        alter table public.daily_user alter column is_admin set not null;
        alter table public.daily_user alter column created_at set default now();
        update public.daily_user set created_at = now() where created_at is null;
        alter table public.daily_user alter column created_at set not null;

        if not exists (
          select 1
          from pg_constraint
          where conrelid = 'public.daily_user'::regclass
            and contype = 'p'
        ) then
          alter table public.daily_user add constraint daily_user_pkey primary key (id);
        end if;

        if not exists (
          select 1
          from pg_constraint
          where conrelid = 'public.daily_user'::regclass
            and conname = 'daily_user_name_required'
        ) then
          alter table public.daily_user
            add constraint daily_user_name_required check (length(trim(name)) > 0);
        end if;
      end if;

      if to_regclass('public.daily_task') is not null then
        alter table public.daily_task alter column id set not null;

        if not exists (
          select 1
          from pg_constraint
          where conrelid = 'public.daily_task'::regclass
            and contype = 'p'
        ) then
          alter table public.daily_task add constraint daily_task_pkey primary key (id);
        end if;
      end if;

      if to_regclass('public.fin_asset') is not null then
        alter table public.fin_asset drop constraint if exists fin_asset_exchange_valid;
      end if;
    end $$;
  `);
}
